CREATE DATABASE QUANLY1

CREATE TABLE CLASSROOM(
BUILDING VARCHAR(10) ,
ROOMNUMBER VARCHAR(10) PRIMARY KEY,
CAPACITY VARCHAR(20)
)
CREATE TABLE DEPARTMENT(
DEPTNAME VARCHAR(20) PRIMARY KEY,
BUILDING VARCHAR(10),
BUDGET VARCHAR(20)
)
CREATE TABLE COURSE(
COURSEID VARCHAR(10) PRIMARY KEY,
TITLE VARCHAR(30),
DEPTNAME VARCHAR(20),
CREDITS VARCHAR(20)
)
CREATE TABLE INSTRUCTOR(
IDINS VARCHAR(10) PRIMARY KEY,
NAMET VARCHAR(20),
DEPTNAME VARCHAR(20),
SALARY VARCHAR(10)
)
CREATE TABLE SECTION(

COURSEID VARCHAR(10),
SECID VARCHAR(10),
SEMESTER VARCHAR(10),
YEART VARCHAR(10),
BUILDING VARCHAR(10),
ROOMNUMBER VARCHAR(10),
TIMESLOTID VARCHAR(10)
)
CREATE TABLE TEACHES(
IDINS VARCHAR(10),
COURSEID VARCHAR(10),
SECID VARCHAR(10),
SEMESTER VARCHAR(10),
YEART VARCHAR(10)

)
CREATE TABLE STUDENT(
IDST VARCHAR(10) PRIMARY KEY,
NAMET VARCHAR(20),
DEPTNAME VARCHAR(20),
TOTCRED VARCHAR(20)
)
CREATE TABLE TAKES(
IDST VARCHAR(10),
COURSEID VARCHAR(10),
SECID VARCHAR(10),
SEMESTER VARCHAR(10),
YEART VARCHAR(10),
GRADE VARCHAR(10),
)

CREATE TABLE ADVISOR(
IDST VARCHAR(10),
IDINS VARCHAR(10)

)
CREATE TABLE TIMESLOT(
TIMESLOTID VARCHAR(10) ,
DAYT  VARCHAR(10),
STARTTIME VARCHAR(10),
ENDTIME VARCHAR(10)
)

CREATE TABLE PREREQ(
PREREQID VARCHAR(10),
COURSEID VARCHAR(10)
)

ALTER TABLE COURSE ADD 
CONSTRAINT FK_DEPART_DNAME FOREIGN KEY(DEPTNAME) REFERENCES DEPARTMENT
ALTER TABLE INSTRUCTOR ADD 
CONSTRAINT FK_INS_DN FOREIGN KEY(DEPTNAME) REFERENCES DEPARTMENT
ALTER TABLE SECTION ADD 
CONSTRAINT FK_COURSE_IDC FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID) ,
CONSTRAINT FK_CLR_RNUM FOREIGN KEY(ROOMNUMBER) REFERENCES CLASSROOM(ROOMNUMBER)

ALTER TABLE TEACHES ADD 
CONSTRAINT FK_I_ID FOREIGN KEY(IDINS) REFERENCES INSTRUCTOR(IDINS),
CONSTRAINT FK_C_ID FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID)

ALTER TABLE STUDENT ADD 
CONSTRAINT FK_STU_DNAME FOREIGN KEY(DEPTNAME) REFERENCES DEPARTMENT(DEPTNAME)
ALTER TABLE TAKES ADD 
CONSTRAINT FK_STU_ID FOREIGN KEY(IDST) REFERENCES STUDENT(IDST),
CONSTRAINT FK_CT_ID FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID)


ALTER TABLE ADVISOR ADD 
CONSTRAINT FK_AI_ID FOREIGN KEY(IDINS) REFERENCES INSTRUCTOR(IDINS),
CONSTRAINT FK_AS_ID FOREIGN KEY(IDST) REFERENCES STUDENT(IDST)

ALTER TABLE PREREQ ADD 
CONSTRAINT FK_CP_ID FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID)



DROP TABLE DEPARTMENT,COURSE,TEACHES,STUDENT,TAKES,ADVISOR,TIMESLOT,PREREQ,INSTRUCTOR,SECTION

DROP TABLE ADVISOR


